import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { ExternalLink } from "lucide-react";
import { MedicalVisual as MedicalVisualType, MedicalImage as MedicalImageType } from "@/lib/mockData";

interface MedicalVisualProps {
    visual: MedicalVisualType;
}

let mermaidInitialized = false;
let mermaidIdCounter = 0;

/**
 * Strip styling directives that the AI sometimes emits (and that frequently arrive
 * corrupted, e.g. "stroke:ﬂ°28a745"), since they break the Mermaid parser. We only
 * want the graph structure (nodes + edges + labels), so removing them lets the
 * diagram render reliably.
 */
export function sanitizeMermaid(code: string): string {
    const unescaped = (code || "")
        // The model / JSON pipeline can leave LITERAL escape sequences ("graph TD\nA[...]")
        // — turn them into real characters so mermaid can parse the graph.
        .replace(/\\r\\n|\\n|\\r/g, "\n")
        .replace(/\\t/g, " ")
        .replace(/\\"/g, '"')
        // strip emojis / variation selectors that crash the parser (keeps Arabic/Latin)
        .replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE00}-\u{FE0F}]/gu, "");
    return unescaped
        .split("\n")
        .filter((line) => !/^\s*(style|classDef|linkStyle|class)\s/i.test(line))
        .map((line) => line.replace(/:::[A-Za-z0-9_-]+/g, "")) // inline class assignments
        .join("\n")
        .trim();
}

/**
 * Renders an AI-authored visual embedded in a medical card.
 * - "mermaid": rendered with the mermaid library (lazy-loaded) into clean SVG.
 * - "svg": rendered through a data: URI <img>, which the browser sandboxes
 *   (no scripts / network) while still playing CSS/SMIL animations.
 * Any failure degrades gracefully (caption only, never breaks the card).
 */
export function MedicalVisual({ visual }: MedicalVisualProps) {
    const [mermaidSvg, setMermaidSvg] = useState<string | null>(null);
    const [failed, setFailed] = useState(false);
    const idRef = useRef(`med-mermaid-${++mermaidIdCounter}`);

    const code = (visual?.code || "").trim();
    const isMermaid = visual?.type === "mermaid";

    useEffect(() => {
        let cancelled = false;
        if (!isMermaid || !code) return;

        (async () => {
            try {
                const mermaid = (await import("mermaid")).default;
                if (!mermaidInitialized) {
                    mermaid.initialize({
                        startOnLoad: false,
                        theme: "neutral",
                        securityLevel: "strict",
                        fontFamily: "inherit",
                    });
                    mermaidInitialized = true;
                }
                const { svg } = await mermaid.render(idRef.current, sanitizeMermaid(code));
                if (!cancelled) setMermaidSvg(svg);
            } catch (err) {
                console.warn("[MedicalVisual] mermaid render failed:", err);
                if (!cancelled) setFailed(true);
            }
        })();

        return () => { cancelled = true; };
    }, [isMermaid, code]);

    if (!code || failed) {
        // Graceful degradation: show only the caption (if any), nothing breaks.
        return visual?.caption ? (
            <p className="text-xs text-slate-400 italic mt-3">{visual.caption}</p>
        ) : null;
    }

    return (
        <motion.figure
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4 }}
            className="mt-4 rounded-2xl border border-[#F1F5F9] bg-[#F8FAFC] p-4 overflow-hidden"
        >
            <div className="w-full overflow-x-auto flex justify-center [&_svg]:max-w-full [&_svg]:h-auto">
                {isMermaid ? (
                    mermaidSvg ? (
                        <div
                            className="medical-mermaid w-full flex justify-center"
                            // mermaid output is generated by the mermaid library from a constrained DSL
                            dangerouslySetInnerHTML={{ __html: mermaidSvg }}
                        />
                    ) : (
                        <div className="h-24 w-full animate-pulse bg-slate-100 rounded-xl" />
                    )
                ) : (
                    <img
                        src={`data:image/svg+xml;utf8,${encodeURIComponent(code)}`}
                        alt={visual.caption || "Medical illustration"}
                        loading="lazy"
                        className="max-h-72 w-auto object-contain"
                        onError={() => setFailed(true)}
                    />
                )}
            </div>
            {visual.caption && (
                <figcaption className="text-xs text-slate-500 italic text-center mt-3">
                    {visual.caption}
                </figcaption>
            )}
        </motion.figure>
    );
}

/**
 * Renders a real reference image resolved server-side (e.g. from Wikipedia),
 * with an attribution link to the source page. Hides itself if the image fails to load.
 */
export function MedicalImageView({ image }: { image: MedicalImageType }) {
    const [failed, setFailed] = useState(false);
    if (!image?.url || failed) return null;

    return (
        <motion.figure
            initial={{ opacity: 0, scale: 0.96 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.4 }}
            className="mt-4 rounded-2xl border border-[#F1F5F9] bg-white p-3 overflow-hidden"
        >
            <div className="w-full flex justify-center bg-[#F8FAFC] rounded-xl overflow-hidden">
                <img
                    src={image.url}
                    alt={image.title || "Medical reference image"}
                    loading="lazy"
                    referrerPolicy="no-referrer"
                    className="max-h-72 w-auto object-contain"
                    onError={() => setFailed(true)}
                />
            </div>
            <figcaption className="flex items-center justify-center gap-1.5 text-[11px] text-slate-400 mt-2">
                {image.title && <span className="text-slate-500">{image.title}</span>}
                {image.pageUrl && (
                    <a
                        href={image.pageUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-1 text-primary hover:underline"
                        onClick={(e) => e.stopPropagation()}
                    >
                        <ExternalLink className="w-3 h-3" />
                        {image.source || "Source"}
                    </a>
                )}
            </figcaption>
        </motion.figure>
    );
}
