import { useMemo } from "react";
import { Download, Check, Clock, FileText, Lightbulb, HelpCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useLanguage } from "@/contexts/LanguageContext";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { cn } from "@/lib/utils";
import { TextWithMath } from "./MathRenderer";

interface SummaryViewProps {
  summary: string | string[];
  title?: string;
  images?: { url: string; description: string; descriptionAr?: string; analyzed?: boolean; title?: string; type?: string; relevance?: string }[];
  formulas?: { name: string; latex: string; description?: string }[];
}

export function SummaryView({ summary, title: initialTitle }: SummaryViewProps) {
  const { toast } = useToast();
  const { language } = useLanguage();
  const isRTL = language === "ar";

  const t = {
    tag: isRTL ? "ملخص" : "Summary",
    readTime: (n: number) => (isRTL ? `${n} دقيقة قراءة` : `${n} min read`),
    tldr: isRTL ? "نظرة عامة سريعة" : "Quick overview",
    inLecture: isRTL ? "في هذه المحاضرة" : "In this lecture",
    takeaways: isRTL ? "أهم ما يجب تذكّره" : "Key takeaways",
    studyTips: isRTL ? "نصائح للمذاكرة" : "Study tips",
    selfCheck: isRTL ? "اختبر فهمك" : "Test yourself",
    terms: isRTL ? "المصطلحات" : "Key terms",
    download: isRTL ? "تحميل PDF" : "Download PDF",
    exporting: isRTL ? "جاري التحضير..." : "Preparing...",
    exportFailed: isRTL ? "فشل التصدير" : "Export Failed",
    fallbackTitle: isRTL ? "ملخص المحاضرة" : "Lecture Summary",
    footer: isRTL ? "ملخص مُنشأ بواسطة LectureMate" : "Summary generated by LectureMate",
  };

  const parsedData = useMemo(() => {
    if (typeof summary !== "string") return null;
    try {
      if (summary.trim().startsWith("{")) return JSON.parse(summary);
    } catch {
      /* not JSON */
    }
    return null;
  }, [summary]);

  const handleExportPDF = async () => {
    const element = document.getElementById("premium-summary-container");
    if (!element) return;
    try {
      toast({ title: t.exporting });
      const canvas = await html2canvas(element, { scale: 2, useCORS: true, backgroundColor: "#ffffff" });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      let heightLeft = pdfHeight;
      let position = 0;
      const pageHeight = pdf.internal.pageSize.getHeight();
      pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);
      heightLeft -= pageHeight;
      while (heightLeft > 0) {
        position = heightLeft - pdfHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, position, pdfWidth, pdfHeight);
        heightLeft -= pageHeight;
      }
      pdf.save(`${(initialTitle || "Summary").replace(/[^a-z0-9]/gi, "_")}.pdf`);
      toast({ title: isRTL ? "تم التصدير بنجاح" : "PDF Exported" });
    } catch {
      toast({ title: t.exportFailed, variant: "destructive" });
    }
  };

  // ---- Plain-text fallback (legacy / non-JSON summaries) ----
  if (!parsedData) {
    const text = typeof summary === "string" ? summary : Array.isArray(summary) ? summary.join("\n") : (isRTL ? "لا يوجد ملخص متاح." : "No summary available.");
    return (
      <div id="premium-summary-container" className="py-6 px-1 sm:px-3" dir={isRTL ? "rtl" : "ltr"}>
        <div className="max-w-4xl mx-auto">
          <article className={cn("bg-white rounded-[28px] border border-slate-200/70 shadow-[0_20px_60px_rgba(0,0,0,0.05)] p-7 md:p-12", isRTL && "text-right")}>
            <h1 className="text-3xl md:text-4xl font-black text-slate-900 mb-6 tracking-tight">{initialTitle || t.fallbackTitle}</h1>
            <div className="text-[15px] leading-[1.9] text-slate-600 font-medium whitespace-pre-wrap">
              <TextWithMath text={text} />
            </div>
          </article>
        </div>
      </div>
    );
  }

  const { mainTitle, subTitle, keyConcepts, definitions, takeawaySummary, takeawayPoints } = parsedData;
  const displayTitle = (mainTitle || initialTitle || t.fallbackTitle).replace(/\.(pdf|pptx?|ppsx|docx?|doc|mp4|webm|mov|avi|mp3|wav|ogg)/gi, "").trim();

  // Prefer the ordered "sections" walkthrough; fall back to keyConcepts for older summaries.
  const sections: { heading: string; content: string }[] =
    Array.isArray(parsedData.sections) && parsedData.sections.length > 0
      ? parsedData.sections
      : Array.isArray(keyConcepts)
        ? keyConcepts.map((c: any) => ({ heading: c.title, content: c.description }))
        : [];

  const points: string[] = Array.isArray(takeawayPoints) ? takeawayPoints : [];
  const defs: { term: string; definition: string }[] = Array.isArray(definitions) ? definitions : [];
  const studyTips: string[] = Array.isArray(parsedData.studyTips) ? parsedData.studyTips : [];
  const selfCheck: string[] = Array.isArray(parsedData.selfCheck) ? parsedData.selfCheck : [];

  const readMin = (() => {
    const all = [takeawaySummary || "", ...sections.map((s) => s.content || ""), ...points, ...defs.map((d) => d.definition || "")].join(" ");
    const words = all.trim().split(/\s+/).filter(Boolean).length;
    return Math.max(1, Math.round(words / 200));
  })();

  return (
    <div id="premium-summary-container" className="py-6 px-1 sm:px-3" dir={isRTL ? "rtl" : "ltr"}>
      <div className="max-w-4xl mx-auto">
        {/* Top bar */}
        <div className={cn("flex items-center justify-between gap-3 mb-6")}>
          <div className={cn("flex items-center gap-2.5")}>
            <span className={cn("inline-flex items-center gap-1.5 text-[11px] font-black uppercase tracking-wider text-[#F05A22] bg-[#F05A22]/10 rounded-full px-3 py-1.5")}>
              <FileText className="w-3.5 h-3.5" /> {t.tag}
            </span>
            <span className={cn("inline-flex items-center gap-1.5 text-xs font-bold text-slate-400")}>
              <Clock className="w-3.5 h-3.5" /> {t.readTime(readMin)}
            </span>
          </div>
          <button
            onClick={handleExportPDF}
            className={cn("no-print inline-flex items-center gap-2 text-sm font-bold text-slate-600 bg-white border border-slate-200 rounded-full px-4 py-2 hover:border-[#F05A22]/40 hover:text-[#F05A22] transition-colors")}
          >
            <Download className="w-4 h-4" /> {t.download}
          </button>
        </div>

        {/* Article */}
        <article className={cn("bg-white rounded-[28px] border border-slate-200/70 shadow-[0_20px_60px_rgba(0,0,0,0.05)] p-7 md:p-12", isRTL ? "text-right" : "text-left")}>
          <h1 className="text-3xl md:text-[40px] font-black text-slate-900 leading-[1.12] tracking-tight">{displayTitle}</h1>
          {subTitle && <p className="mt-3 text-lg text-slate-500 font-medium leading-relaxed">{subTitle}</p>}

          {/* TL;DR */}
          {takeawaySummary && (
            <div className="mt-8 rounded-2xl bg-[#F05A22]/[0.05] border-s-4 border-[#F05A22] p-5">
              <p className="text-[11px] font-black uppercase tracking-wider text-[#F05A22] mb-2">{t.tldr}</p>
              <div className="text-[15px] leading-[1.8] text-slate-700 font-medium">
                <TextWithMath text={takeawaySummary} />
              </div>
            </div>
          )}

          {/* Walkthrough sections */}
          {sections.length > 0 && (
            <div className="mt-10">
              <h2 className="text-xl font-black text-slate-900 mb-7 flex items-center gap-2.5">
                <span className="w-1.5 h-6 rounded-full bg-[#F05A22]" />
                {t.inLecture}
              </h2>
              <div className="space-y-8">
                {sections.map((s, i) => (
                  <div key={i}>
                    <h3 className="text-[17px] font-black text-slate-900 mb-2 flex items-baseline gap-2.5">
                      <span className="font-mono text-sm text-[#F05A22] shrink-0">{String(i + 1).padStart(2, "0")}</span>
                      <span>{s.heading}</span>
                    </h3>
                    <div className="text-[15px] leading-[1.85] text-slate-600 ps-[2.1rem]">
                      <TextWithMath text={s.content} />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Extras grid — kept side-by-side so the page stays compact, not one long column */}
          {(points.length > 0 || studyTips.length > 0 || selfCheck.length > 0 || defs.length > 0) && (
            <div className="mt-10 grid sm:grid-cols-2 gap-5 items-start">
              {/* Key takeaways */}
              {points.length > 0 && (
                <div className="rounded-2xl bg-slate-50 border border-slate-100 p-6">
                  <h2 className="text-sm font-black text-slate-900 mb-4 flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600" /> {t.takeaways}
                  </h2>
                  <ul className="space-y-3">
                    {points.map((p, i) => (
                      <li key={i} className="flex items-start gap-2.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 shrink-0 mt-2" />
                        <div className="text-[14px] leading-relaxed text-slate-700 font-medium flex-1">
                          <TextWithMath text={p} />
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Study tips */}
              {studyTips.length > 0 && (
                <div className="rounded-2xl bg-[#FFF7ED] border border-[#F05A22]/15 p-6">
                  <h2 className="text-sm font-black text-slate-900 mb-4 flex items-center gap-2">
                    <Lightbulb className="w-4 h-4 text-[#F05A22]" /> {t.studyTips}
                  </h2>
                  <ul className="space-y-3">
                    {studyTips.map((p, i) => (
                      <li key={i} className="flex items-start gap-2.5">
                        <span className="w-1.5 h-1.5 rounded-full bg-[#F05A22] shrink-0 mt-2" />
                        <div className="text-[14px] leading-relaxed text-slate-700 font-medium flex-1">
                          <TextWithMath text={p} />
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Test yourself */}
              {selfCheck.length > 0 && (
                <div className="rounded-2xl bg-white border border-slate-200/70 p-6">
                  <h2 className="text-sm font-black text-slate-900 mb-4 flex items-center gap-2">
                    <HelpCircle className="w-4 h-4 text-violet-500" /> {t.selfCheck}
                  </h2>
                  <ul className="space-y-3">
                    {selfCheck.map((q, i) => (
                      <li key={i} className="flex items-start gap-2.5">
                        <span className="text-xs font-black text-violet-500 shrink-0 mt-0.5 tabular-nums">{i + 1}.</span>
                        <div className="text-[14px] leading-relaxed text-slate-600 font-medium flex-1">
                          <TextWithMath text={q} />
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Key terms */}
              {defs.length > 0 && (
                <div className="rounded-2xl bg-white border border-slate-200/70 p-6">
                  <h2 className="text-sm font-black text-slate-900 mb-4 flex items-center gap-2">
                    <FileText className="w-4 h-4 text-slate-400" /> {t.terms}
                  </h2>
                  <dl className="space-y-3.5">
                    {defs.map((d, i) => (
                      <div key={i} className="border-s-2 border-slate-200 ps-3">
                        <dt className="font-black text-slate-900 text-[14px]">{d.term}</dt>
                        <dd className="text-slate-500 text-[13px] mt-0.5 leading-relaxed">
                          <TextWithMath text={d.definition} />
                        </dd>
                      </div>
                    ))}
                  </dl>
                </div>
              )}
            </div>
          )}
        </article>

        <p className="text-center text-[11px] text-slate-300 font-bold mt-6">{t.footer}</p>
      </div>
    </div>
  );
}
